# Generated by Django 4.0.6 on 2022-11-18 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriptions_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=250)),
                ('channel_address', models.CharField(max_length=250)),
                ('channel_avatar', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Video_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=250)),
                ('video_address', models.CharField(max_length=250)),
                ('video_thumbnails', models.CharField(max_length=250)),
                ('video_title', models.CharField(max_length=250)),
                ('video_duration', models.CharField(max_length=250)),
                ('video_hide', models.BooleanField()),
                ('video_watch', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('authors', models.ManyToManyField(to='manager.author')),
            ],
        ),
    ]
