# Generated by Django 4.0.6 on 2022-11-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=250)),
                ('refresh_token', models.CharField(max_length=250)),
                ('id_token', models.CharField(max_length=250)),
                ('token_uri', models.CharField(max_length=250)),
                ('client_id', models.CharField(max_length=250)),
                ('client_secret', models.CharField(max_length=250)),
                ('scopes', models.CharField(max_length=250)),
            ],
        ),
    ]
