# Generated by Django 4.0.6 on 2022-11-19 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_credentials',
        ),
    ]
